
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  <<: *default
  database: bitcoins_app_development

test:
  <<: *default
  database: bitcoins_app_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["BITCOINS_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["BITCOINS_APP_DATABASE_PASSWORD"] %>
  port: <%= ENV["BITCOINS_APP_PORT"] %>
